# Generated by Django 5.0.3 on 2024-03-25 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="client",
        ),
        migrations.RemoveField(
            model_name="project",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="project",
            name="users",
        ),
        migrations.AlterField(
            model_name="client",
            name="client_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="project",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="project_name",
            field=models.CharField(max_length=50),
        ),
    ]
